[2024-10-16T13:32:24.676+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T13:32:24.687+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: linear_dag.make_predictions manual__2024-10-16T08:02:20.723623+00:00 [queued]>
[2024-10-16T13:32:24.695+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: linear_dag.make_predictions manual__2024-10-16T08:02:20.723623+00:00 [queued]>
[2024-10-16T13:32:24.696+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-16T13:32:24.712+0530] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): make_predictions> on 2024-10-16 08:02:20.723623+00:00
[2024-10-16T13:32:24.720+0530] {standard_task_runner.py:72} INFO - Started process 7405 to run task
[2024-10-16T13:32:24.730+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'linear_dag', 'make_predictions', 'manual__2024-10-16T08:02:20.723623+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/linear_dag.py', '--cfg-path', '/tmp/tmplrf7rijt']
[2024-10-16T13:32:24.734+0530] {standard_task_runner.py:105} INFO - Job 42: Subtask make_predictions
[2024-10-16T13:32:24.815+0530] {task_command.py:467} INFO - Running <TaskInstance: linear_dag.make_predictions manual__2024-10-16T08:02:20.723623+00:00 [running]> on host tce.myguest.virtualbox.org
[2024-10-16T13:32:24.886+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='linear_dag' AIRFLOW_CTX_TASK_ID='make_predictions' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T08:02:20.723623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T08:02:20.723623+00:00'
[2024-10-16T13:32:24.889+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-16T13:32:24.889+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-16T13:32:24.890+0530] {logging_mixin.py:190} INFO - Current task name:make_predictions state:running start_date:2024-10-16 08:02:24.687832+00:00
[2024-10-16T13:32:24.890+0530] {logging_mixin.py:190} INFO - Dag name:linear_dag and current dag run status:running
[2024-10-16T13:32:24.890+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T13:32:45.198+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/vboxuser/airflow/dags/linear_dag.py", line 34, in make_predictions
    raise ValueError(f"'{actual_output_column}' column not found in the CSV file.")
ValueError: 'price' column not found in the CSV file.
[2024-10-16T13:32:45.224+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-16T13:32:45.234+0530] {logging_mixin.py:190} INFO - Task start:2024-10-16 08:02:24.687832+00:00 end:2024-10-16 08:02:45.223549+00:00 duration:20.535717
[2024-10-16T13:32:45.235+0530] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): make_predictions> dag:<DAG: linear_dag> dagrun:<DagRun linear_dag @ 2024-10-16 08:02:20.723623+00:00: manual__2024-10-16T08:02:20.723623+00:00, state:running, queued_at: 2024-10-16 08:02:20.742736+00:00. externally triggered: True>
[2024-10-16T13:32:45.236+0530] {logging_mixin.py:190} INFO - Failure caused by 'price' column not found in the CSV file.
[2024-10-16T13:32:45.236+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=linear_dag, task_id=make_predictions, run_id=manual__2024-10-16T08:02:20.723623+00:00, execution_date=20241016T080220, start_date=20241016T080224, end_date=20241016T080245
[2024-10-16T13:32:45.257+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T13:32:45.258+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task make_predictions ('price' column not found in the CSV file.; 7405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/vboxuser/airflow/dags/linear_dag.py", line 34, in make_predictions
    raise ValueError(f"'{actual_output_column}' column not found in the CSV file.")
ValueError: 'price' column not found in the CSV file.
[2024-10-16T13:32:45.291+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-16T13:32:45.329+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T13:32:45.330+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
